### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by michaellarabel** [intel/BaseKit-code-samples#1]
Hi, pardon if this wouldn't be the most relevant repository regarding oneAPI/DPC++ for the inquiry/request, but just wondering if any of the existing or planned code samples would work well for benchmarking purposes? In terms of either comparing oneAPI changes and/or hardware component comparisons for evaluating capabilities of the oneAPI base kit.

I am already using some oneAPI components like Embree/OSPray/OIDn for hardware performance testing but curious if there are any existing/planned other test cases for the base oneAPI that would work well for benchmarking purposes.

Thanks!
Michael

**Comment by Jenn500** [comment]
Thanks for the interesting question, if there are any specific performance and source related details or concerns, please use the support forum for reporting issues at https://software.intel.com/en-us/oneapi/support.

Currently the oneAPI toolkits are Beta products, the code samples require the Intel oneAPI Base Toolkit beta. Please read the Intel End User License Agreement for Developer Tools (https://software.intel.com/en-us/license/end-user-license-for-developer-tools) (Version September 2019) section 4.2 on pre-release product usage.  At this time the code samples cannot be used for benchmarking. They’re used for showing the programming How To only.  

For further questions, please go to the oneAPI forum https://software.intel.com/en-us/oneapi/support. 

Thanks,
Jennifer

**Comment by Jenn500** [comment]
Mark this question as closed.
