### ISSUE TITLE
centos7 build error

### ISSUE THREAD

**Issue by cdyangzhenyu** [intel/BaseKit-code-samples#2]
[root@Machine build]# make fpga_emu
Linking CXX executable ../crr.fpga_emu
Error: No input file detected
/tmp/main-f3dadf.o: file not recognized: File truncated
clang++: error: fpga compiler command failed with exit code 1 (use -v to see invocation)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [crr.fpga_emu] Error 1
make[2]: *** [src/CMakeFiles/crr.fpga_emu.dir/all] Error 2
make[1]: *** [src/CMakeFiles/fpga_emu.dir/rule] Error 2
make: *** [fpga_emu] Error 2

**Comment by ShubhamChaudhari-Intel** [comment]
Hi,
Thanks for contacting us. Your question is related to FPGA emulator and for that, we have separate FPGA forum. You can post your query [here](https://forums.intel.com/s/topic/0TO0P0000001AUUWA2/intel-high-level-design?language=en_US).

- Shubham
