### ISSUE TITLE
VPL sample build failure - missing vpl.hpp

### ISSUE THREAD

**Issue by bbao3** [intel/BaseKit-code-samples#6]
Hi, I installed the latest oneAPI Base Toolkit, and followed the instruction to configure my VS2017 environment. But when I try to build the VPL sample (simple_decode for example), it will be blocked by missing "vpl/vpl.hpp". I can't find it either in the sample folder or oneapi installation folder. How can I fix this issue？

**Comment by Jenn500** [comment]
Please check if this folder "C:\Program Files (x86)\inteloneapi\vpl\latest\include" exits, it should be added to the sample project's property. Or you can follow the readme.md's build instruction.

**Comment by bbao3** [comment]
Thank you, Jennifer. The strange thing is I can't find this folder ("C:\Program Files (x86)\inteloneapi\vpl"). I think this is not an issue of sample, but the issue of the installation package (w_BaseKit_b_2021.1.3.085). I've select all the components including VPL while installing this package but there is no such a VPL folder in the installation path.

**Comment by bbao3** [comment]
Hi Jennifer, the issue had been solved, thanks. There are some errors during installation - "some rpm package failed to be downloaded successfully". After refining the network connection and re-installation the issue was gone.
